### PR TITLE
Covid Resources India Logo

### LINKED ISSUE #3: Make a logo / icon for this app
Just make sure it is friendly with IDK, good colors maybe? Some colors I chose are [here](https://github.com/Illusion47586/covid_resources-india/blob/master/lib/core/theme/colors.dart), and the font is [manrope](https://fonts.google.com/specimen/Manrope?query=manrope).

### PR DESCRIPTION
**Pull request by jameskorah**
This PR ``closes #3`` 
* *Uploaded a "Covid Resources" logo* to the "images folder"`.`

### CODE REVIEW

**Comment by Illusion47586** [comment]
Alright @jameskorah a few tweaks and we should be good to go.

1. Remove the text thing from the icon. The image is to be used as an icon, so it would already have a label.
2. Remove the background from the image. (upload png)

**Comment by jameskorah** [comment]
Hello @Illusion47586,

  1. I've removed the text below the initial image
  2. I've reuploaded the image as a PNG file without the huge background

**Comment by Illusion47586** [comment]
Alright cool, I'll put the image in the right place. Thanks for the contribution🎉.

**Review by Illusion47586 — COMMENTED** [review]
Added icon

**Pull request merged**
